return {
    Clicking = {
        Difficulty = 1, 
        Description = "Click %s times!", 
        Multiplier = "Crit Power", 
        Requirement = "Clicks", 
        Tasks = {
            [1] = {
                Title = "Clicking I", 
                Amount = 300000, 
                BadgeId = 4.215306827528778E15, 
                BadgeIcon = 102820106103666, 
                Reward = {
                    Gems = 50000, 
                    Multipliers = {
                        CriticalPower = 1.05
                    }
                }
            }, 
            [2] = {
                Title = "Clicking II", 
                Amount = 1000000, 
                BadgeId = 129239546987283, 
                BadgeIcon = 133873970064420, 
                Reward = {
                    Gems = 350000000000, 
                    Multipliers = {
                        CriticalPower = 1.07
                    }
                }
            }, 
            [3] = {
                Title = "Clicking III", 
                Amount = 40000000, 
                BadgeId = 2.222568444823194E15, 
                BadgeIcon = 137610776379701, 
                Reward = {
                    Gems = 650000000000, 
                    Multipliers = {
                        CriticalPower = 1.09
                    }
                }
            }, 
            [4] = {
                Title = "Clicking IV", 
                Amount = 500000000, 
                BadgeId = 2.104433829228223E15, 
                BadgeIcon = 114122960600455, 
                Reward = {
                    Gems = 1150000000000, 
                    Multipliers = {
                        CriticalPower = 1.11
                    }
                }
            }
        }
    }, 
    Eggs = {
        Difficulty = 1, 
        Description = "Hatch %s Eggs!", 
        Multiplier = "Egg Speed", 
        Requirement = "Eggs Hatched", 
        Tasks = {
            [1] = {
                Title = "Hatcher I", 
                Amount = 300, 
                BadgeId = 2.384405279562925E15, 
                BadgeIcon = 80909842039137, 
                Reward = {
                    Multipliers = {
                        EggOpenSpeed = 1.02
                    }
                }
            }, 
            [2] = {
                Title = "Hatcher II", 
                Amount = 15000, 
                BadgeId = 3.870372295308155E15, 
                BadgeIcon = 73892847238638, 
                Reward = {
                    Multipliers = {
                        EggOpenSpeed = 1.02
                    }
                }
            }, 
            [3] = {
                Title = "Hatcher III", 
                Amount = 150000, 
                BadgeId = 3.285315880896998E15, 
                BadgeIcon = 131474219442837, 
                Reward = {
                    Multipliers = {
                        EggOpenSpeed = 1.03
                    }
                }
            }, 
            [4] = {
                Title = "Hatcher IV", 
                Amount = 500000, 
                BadgeId = 301540243048835, 
                BadgeIcon = 81066473167315, 
                Reward = {
                    Multipliers = {
                        EggOpenSpeed = 1.04
                    }
                }
            }, 
            [5] = {
                Title = "Hatcher V", 
                Amount = 1500000, 
                BadgeId = 2.044506302043991E15, 
                BadgeIcon = 123003743904321, 
                Reward = {
                    Multipliers = {
                        EggOpenSpeed = 1.03
                    }
                }
            }, 
            [6] = {
                Title = "Hatcher VI", 
                Amount = 3000000, 
                BadgeId = 3.88425607371025E15, 
                BadgeIcon = 80507228754799, 
                Reward = {
                    Multipliers = {
                        EggOpenSpeed = 1.05
                    }
                }
            }, 
            [7] = {
                Title = "Hatcher VII", 
                Amount = 15000000, 
                BadgeId = 3.45569384141993E15, 
                BadgeIcon = 129693268845552, 
                Reward = {
                    Multipliers = {
                        EggOpenSpeed = 1.05
                    }
                }
            }
        }
    }, 
    Mythics = {
        Difficulty = 3, 
        Description = "Hatch %s Mythical pets!", 
        Multiplier = "Secret Luck", 
        Requirement = "Secrets Discovered", 
        Tasks = {
            [1] = {
                Title = "Mythics Hunter I", 
                Amount = 2, 
                BadgeId = 3.09490089324994E15, 
                BadgeIcon = 116551253579688, 
                Reward = {
                    Multipliers = {
                        SecretLuck = 1.05
                    }
                }
            }, 
            [2] = {
                Title = "Mythics Hunter II", 
                Amount = 7, 
                BadgeId = 2.167700006996859E15, 
                BadgeIcon = 90014133351310, 
                Reward = {
                    Multipliers = {
                        SecretLuck = 1.08
                    }
                }
            }, 
            [3] = {
                Title = "Mythics Hunter III", 
                Amount = 13, 
                BadgeId = 1.418885290299305E15, 
                BadgeIcon = 96643689314196, 
                Reward = {
                    Multipliers = {
                        SecretLuck = 1.12
                    }
                }
            }, 
            [4] = {
                Title = "Mythics Hunter IV", 
                Amount = 20, 
                BadgeId = 2.407214207938011E15, 
                BadgeIcon = 133178725549057, 
                Reward = {
                    Multipliers = {
                        SecretLuck = 1.18
                    }
                }
            }
        }
    }, 
    Collection = {
        Difficulty = 2, 
        Description = "Collect %s unique pets!", 
        Requirement = "Pets Discovered", 
        Tasks = {
            [1] = {
                Title = "Collector I", 
                Amount = 26, 
                BadgeId = 866406020093047, 
                BadgeIcon = 117634858945169, 
                Reward = {
                    Equips = 1, 
                    Multipliers = {
                        PetTrainerExp = 1.05
                    }
                }
            }, 
            [2] = {
                Title = "Collector II", 
                Amount = 65, 
                BadgeId = 536258652946628, 
                BadgeIcon = 130856771179405, 
                Reward = {
                    Storage = 20, 
                    Multipliers = {
                        PetTrainerExp = 1.1
                    }
                }
            }, 
            [3] = {
                Title = "Collector III", 
                Amount = 130, 
                BadgeId = 0, 
                BadgeIcon = 0, 
                Reward = {
                    Storage = 30, 
                    Multipliers = {
                        PetTrainerExp = 1.15
                    }
                }
            }, 
            [4] = {
                Title = "Collector IV", 
                Amount = 260, 
                BadgeId = 0, 
                BadgeIcon = 0, 
                Reward = {
                    Storage = 40, 
                    Multipliers = {
                        PetTrainerExp = 1.2
                    }
                }
            }
        }
    }, 
    GoldenCrafts = {
        Difficulty = 2, 
        Description = "Create %s Golden pets!", 
        Multiplier = "Golden Luck", 
        Requirement = "Goldens Crafted", 
        Tasks = {
            [1] = {
                Title = "Golden I", 
                Amount = 5, 
                BadgeId = 3.087356992571808E15, 
                BadgeIcon = 71136019751005, 
                Reward = {
                    Multipliers = {
                        GoldenLuck = 1.05
                    }
                }
            }, 
            [2] = {
                Title = "Golden II", 
                Amount = 200, 
                BadgeId = 1.883116693741865E15, 
                BadgeIcon = 137560986619020, 
                Reward = {
                    Multipliers = {
                        GoldenLuck = 1.05
                    }
                }
            }, 
            [3] = {
                Title = "Golden III", 
                Amount = 500, 
                BadgeId = 2.888728890154294E15, 
                BadgeIcon = 109189913030048, 
                Reward = {
                    Multipliers = {
                        GoldenLuck = 1.6
                    }
                }
            }, 
            [4] = {
                Title = "Golden IV", 
                Amount = 1000, 
                BadgeId = 3.661099587666617E15, 
                BadgeIcon = 123323513115679, 
                Reward = {
                    Multipliers = {
                        GoldenLuck = 1.7
                    }
                }
            }
        }
    }, 
    QuestBadges = {
        Difficulty = 1, 
        Description = "Complete %s Quests!", 
        Multiplier = "More Tokens", 
        Requirement = "Quests", 
        Tasks = {
            [1] = {
                Title = "Quest I", 
                Amount = 13, 
                BadgeId = 2.502103871376663E15, 
                BadgeIcon = 137099287679326, 
                Reward = {
                    Tokens = 5, 
                    Multipliers = {
                        TokenYield = 1.01
                    }
                }
            }, 
            [2] = {
                Title = "Quest II", 
                Amount = 65, 
                BadgeId = 312012651977766, 
                BadgeIcon = 80099901144638, 
                Reward = {
                    Tokens = 10, 
                    Multipliers = {
                        TokenYield = 1.03
                    }
                }
            }, 
            [3] = {
                Title = "Quest III", 
                Amount = 325, 
                BadgeId = 3.28245173747725E15, 
                BadgeIcon = 138497706099685, 
                Reward = {
                    Tokens = 15, 
                    Multipliers = {
                        TokenYield = 1.03
                    }
                }
            }, 
            [4] = {
                Title = "Quest IV", 
                Amount = 1300, 
                BadgeId = 1.30407325834156E15, 
                BadgeIcon = 78094552105163, 
                Reward = {
                    Tokens = 25, 
                    Multipliers = {
                        TokenYield = 1.04
                    }
                }
            }, 
            [5] = {
                Title = "Quest GOD", 
                Amount = 6500, 
                BadgeId = 1.448876578739769E15, 
                BadgeIcon = 100168271951821, 
                Reward = {
                    Tokens = 40, 
                    Multipliers = {
                        TokenYield = 1.1
                    }
                }
            }
        }
    }
};