return {
    FriendBoost = {
        Duration = 0, 
        Name = "Friend Luck Boost", 
        Type = "FriendBoost", 
        Rarity = "Rare", 
        Image = "rbxassetid://105676641029847", 
        Description = "Gives a <font color=\"#00ff00\">Luck Boost</font> when playing with <font color=\"#ffaa00\">Friends</font>"
    }, 
    Luck20 = {
        Duration = 300, 
        Name = "Luck Potion I", 
        Type = "Luck", 
        Multi = 1.25, 
        Rarity = "Rare", 
        Image = "rbxassetid://102883812352062", 
        Description = "Gives <font color=\"#00ff00\">+x1.25 Luck</font> on <font color=\"#ffaa00\">Eggs</font>"
    }, 
    ["Luck Potion II"] = {
        Duration = 900, 
        Name = "Luck Potion II", 
        Type = "Luck", 
        Multi = 1.35, 
        Rarity = "Epic", 
        Image = "rbxassetid://134463651548499", 
        Description = "Gives <font color=\"#00ff00\">+x1.35 Luck</font> on <font color=\"#ffaa00\">Eggs</font>"
    }, 
    ["Luck Potion III"] = {
        Duration = 900, 
        Name = "Luck Potion III", 
        Type = "Luck", 
        Multi = 1.55, 
        Rarity = "Mythical", 
        Image = "rbxassetid://70450071782595", 
        Description = "Gives <font color=\"#00ff00\">+x1.55 Luck</font> on <font color=\"#ffaa00\">Eggs</font>"
    }, 
    ["Tap Potion"] = {
        Name = "Tap Potion I", 
        Duration = 600, 
        Type = "Taps", 
        Multi = 0.15, 
        Image = "rbxassetid://87417436260695", 
        Rarity = "Common", 
        Description = "Gives <font color=\"#00ff00\">+15% Increase</font> on <font color=\"#ffaa00\">Clicks</font>"
    }, 
    ["Tap Potion II"] = {
        Name = "Tap Potion II", 
        Duration = 900, 
        Type = "Taps", 
        Multi = 0.5, 
        Image = "rbxassetid://91050515569377", 
        Rarity = "Rare", 
        Description = "Gives <font color=\"#00ff00\">+50% Increase</font> on <font color=\"#ffaa00\">Clicks</font>"
    }, 
    ["Tap Potion III"] = {
        Name = "Tap Potion III", 
        Duration = 1200, 
        Type = "Taps", 
        Multi = 1, 
        Image = "rbxassetid://70657594833668", 
        Rarity = "Mythical", 
        Description = "Gives <font color=\"#00ff00\">+100% Increase</font> on <font color=\"#ffaa00\">Clicks</font>"
    }, 
    ["Gem Potion I"] = {
        Name = "Gem Potion I", 
        Duration = 600, 
        Type = "Gems", 
        Multi = 0.5, 
        Image = "rbxassetid://88634684974540", 
        Rarity = "Rare", 
        Description = "Gives <font color=\"#00ff00\">+50% Increase</font> on <font color=\"#00ff00\">Gems</font>"
    }, 
    ["Gem Potion II"] = {
        Name = "Gem Potion II", 
        Duration = 900, 
        Type = "Gems", 
        Multi = 0.75, 
        Image = "rbxassetid://88634684974540", 
        Rarity = "Epic", 
        Description = "Gives <font color=\"#00ff00\">+75% Increase</font> on <font color=\"#00ff00\">Gems</font>"
    }, 
    ["Gem Potion III"] = {
        Name = "Gem Potion III", 
        Duration = 1200, 
        Type = "Gems", 
        Multi = 0.8, 
        Image = "rbxassetid://88634684974540", 
        Rarity = "Legendary", 
        Description = "Gives <font color=\"#00ff00\">+80% Increase</font> on <font color=\"#00ff00\">Gems</font>"
    }, 
    ["Rebirth Potion I"] = {
        Name = "Rebirth Potion I", 
        Duration = 600, 
        Type = "Rebirths", 
        Multi = 0.1, 
        Image = "rbxassetid://88634684974540", 
        Rarity = "Rare", 
        Description = "Gives <font color=\"#00ff00\">+10% Increase</font> on <font color=\"#ffaa00\">Rebirths</font>"
    }, 
    ["Rebirth Potion II"] = {
        Name = "Rebirth Potion II", 
        Duration = 900, 
        Type = "Rebirths", 
        Multi = 0.2, 
        Image = "rbxassetid://88634684974540", 
        Rarity = "Epic", 
        Description = "Gives <font color=\"#00ff00\">+20% Increase</font> on <font color=\"#ffaa00\">Rebirths</font>"
    }, 
    ["Rebirth Potion III"] = {
        Name = "Rebirth Potion III", 
        Duration = 1200, 
        Type = "Rebirths", 
        Multi = 0.3, 
        Image = "rbxassetid://88634684974540", 
        Rarity = "Legendary", 
        Description = "Gives <font color=\"#00ff00\">+30% Increase</font> on <font color=\"#ffaa00\">Rebirths</font>"
    }, 
    ["Egg Incubator"] = {
        Name = "Egg Incubator", 
        Duration = 50, 
        Type = "TripleHatch", 
        Image = "rbxassetid://85444154079768", 
        Rarity = "Legendary", 
        Description = "A machine that allows you to hatch <font color=\"#FFFF00\">3x Eggs</font>"
    }, 
    ["Octo Incubator"] = {
        Name = "Octo Incubator", 
        Duration = 900, 
        Type = "OctoHatch", 
        Image = "rbxassetid://118139607016562", 
        Rarity = "Mythic", 
        Description = "A machine that allows you to hatch <font color=\"#FFFF00\">8x Eggs</font>"
    }, 
    ServerLuck = {
        Name = "Server Luck", 
        Duration = 0, 
        Type = "ServerLuck", 
        Rarity = "Mythic", 
        Image = "rbxassetid://99783720056712", 
        Description = "Server-wide <font color=\"#00ff00\">Luck Boost</font> purchased by players"
    }, 
    TacoPotion = {
        Duration = 300, 
        Name = "Taco Potion", 
        Type = "Luck", 
        Multi = 8, 
        Rarity = "Mythic", 
        Image = "rbxassetid://102598336043065", 
        Description = "Gives <font color=\"#00ff00\">+x8 Luck</font> on <font color=\"#ffaa00\">Eggs</font>"
    }, 
    ["Festive Luck I"] = {
        Duration = 300, 
        Name = "Festive Luck I", 
        Type = "Luck", 
        Multi = 3, 
        Rarity = "Mythic", 
        Image = "rbxassetid://85691865305797", 
        Description = "Gives <font color=\"#00ff00\">+x3 Luck</font> on <font color=\"#ffaa00\">Eggs</font>"
    }, 
    ["Festive Luck II"] = {
        Duration = 300, 
        Name = "Festive Luck II", 
        Type = "Luck", 
        Multi = 6, 
        Rarity = "Mythic", 
        Image = "rbxassetid://101342536275160", 
        Description = "Gives <font color=\"#00ff00\">+x6 Luck</font> on <font color=\"#ffaa00\">Eggs</font>"
    }, 
    ["Festive Tap I"] = {
        Duration = 300, 
        Name = "Festive Tap I", 
        Type = "Taps", 
        Multi = 3, 
        Rarity = "Mythic", 
        Image = "rbxassetid://113595316895928", 
        Description = "Gives <font color=\"#00ff00\">x3 Clicks</font> when <font color=\"#ffaa00\">Tapping</font>"
    }, 
    ["Festive Rebirths I"] = {
        Duration = 240, 
        Name = "Festive Rebirths I", 
        Type = "Rebirths", 
        Multi = 2, 
        Rarity = "Mythic", 
        Image = "rbxassetid://138752297199840", 
        Description = "Gives <font color=\"#00ff00\">x2 Rebirths</font> when <font color=\"#ffaa00\">Rebirthing</font>"
    }
};