return {
    Main = {
        Prices = {
            [1] = 100, 
            [2] = 4000, 
            [3] = 35000, 
            [4] = 400000, 
            [5] = 500000, 
            [6] = 600000, 
            [7] = 700000, 
            [8] = 800000
        }, 
        IslandRequirements = {
            Spawn = 2, 
            Winter = 4, 
            Desert = 6, 
            Jungle = 7, 
            Heaven = 8
        }
    }
};