return {
    Default = {}, 
    Legendary = {
        timingMultiplier = 1.5, 
        chargeUp = {
            wobbleCount = 4, 
            wobbleRotationDegrees = 22
        }
    }, 
    Mythical = {
        timingMultiplier = 2, 
        petDisplayTime = 4, 
        chargeUp = {
            wobbleCount = 5, 
            wobbleRotationDegrees = 22
        }
    }, 
    Secret = {
        timingMultiplier = 2, 
        petDisplayTime = 7, 
        chargeUp = {
            wobbleCount = 5, 
            wobbleRotationDegrees = 22
        }
    }
};