return {
    Spawn = {
        Lighting = {
            ClockTime = 12
        }, 
        Atmosphere = {
            Density = game.Lighting.Atmosphere.Density, 
            Color = game.Lighting.Atmosphere.Color, 
            Decay = game.Lighting.Atmosphere.Decay
        }
    }, 
    Forest = {
        Lighting = {
            ClockTime = 12
        }, 
        Atmosphere = {
            Density = game.Lighting.Atmosphere.Density, 
            Color = game.Lighting.Atmosphere.Color, 
            Decay = game.Lighting.Atmosphere.Decay
        }
    }, 
    Desert = {
        Lighting = {
            ClockTime = 12
        }, 
        Atmosphere = {
            Density = 0.3, 
            Color = Color3.fromRGB(255, 222, 211), 
            Decay = Color3.fromRGB(255, 207, 184)
        }
    }, 
    Heaven = {
        Lighting = {
            ClockTime = 10
        }, 
        Atmosphere = {
            Density = 0.24, 
            Color = Color3.fromRGB(255, 255, 255), 
            Decay = Color3.fromRGB(255, 207, 184)
        }
    }, 
    Winter = {
        Lighting = {
            ClockTime = 11.5
        }, 
        Atmosphere = {
            Density = 0.33, 
            Color = Color3.fromRGB(175, 223, 255), 
            Decay = Color3.fromRGB(0, 76, 255)
        }
    }, 
    Jungle = {
        Lighting = {
            ClockTime = 11.5
        }, 
        Atmosphere = {
            Density = 0.27, 
            Color = Color3.fromRGB(184, 255, 171), 
            Decay = Color3.fromRGB(53, 102, 0)
        }
    }, 
    Volcano = {
        Lighting = {
            ClockTime = 6
        }, 
        Atmosphere = {
            Density = 0.35, 
            Color = Color3.fromRGB(255, 132, 84), 
            Decay = Color3.fromRGB(255, 180, 180)
        }
    }, 
    Crystal = {
        Lighting = {
            ClockTime = 6
        }, 
        Atmosphere = {
            Density = 0.3, 
            Color = Color3.fromRGB(104, 104, 104), 
            Decay = Color3.fromRGB(255, 180, 180)
        }
    }, 
    Pirate = {
        Lighting = {
            ClockTime = 15
        }, 
        Atmosphere = {
            Density = 0.45, 
            Color = Color3.fromRGB(0, 132, 255), 
            Decay = Color3.fromRGB(0, 208, 255)
        }
    }, 
    Candy = {
        Lighting = {
            ClockTime = 12
        }, 
        Atmosphere = {
            Density = 0.3, 
            Color = Color3.fromRGB(255, 175, 254), 
            Decay = Color3.fromRGB(255, 207, 184)
        }
    }, 
    Atlantis = {
        Lighting = {
            ClockTime = 12
        }, 
        Atmosphere = {
            Density = 0.3, 
            Color = Color3.fromRGB(0, 115, 255), 
            Decay = Color3.fromRGB(125, 177, 255)
        }
    }, 
    Space = {
        Lighting = {
            ClockTime = 0
        }, 
        Atmosphere = {
            Density = 0.3, 
            Color = Color3.fromRGB(50, 0, 39), 
            Decay = Color3.fromRGB(69, 54, 143)
        }
    }
};