return {
    AA = {
        Emoji = "\240\159\143\179\239\184\143", 
        Name = "Hidden"
    }, 
    TJ = {
        Emoji = "\240\159\135\185\240\159\135\175", 
        Name = "Tajikistan"
    }, 
    HR = {
        Emoji = "\240\159\135\173\240\159\135\183", 
        Name = "Croatia"
    }, 
    KE = {
        Emoji = "\240\159\135\176\240\159\135\170", 
        Name = "Kenya"
    }, 
    CR = {
        Emoji = "\240\159\135\168\240\159\135\183", 
        Name = "CostaRica"
    }, 
    BR = {
        Emoji = "\240\159\135\167\240\159\135\183", 
        Name = "Brazil"
    }, 
    SB = {
        Emoji = "\240\159\135\184\240\159\135\167", 
        Name = "SolomonIslands"
    }, 
    BJ = {
        Emoji = "\240\159\135\167\240\159\135\175", 
        Name = "Benin"
    }, 
    TR = {
        Emoji = "\240\159\135\185\240\159\135\183", 
        Name = "Turkey"
    }, 
    PR = {
        Emoji = "\240\159\135\181\240\159\135\183", 
        Name = "PuertoRico"
    }, 
    UZ = {
        Emoji = "\240\159\135\186\240\159\135\191", 
        Name = "Uzbekistan"
    }, 
    MR = {
        Emoji = "\240\159\135\178\240\159\135\183", 
        Name = "Mauritania"
    }, 
    MM = {
        Emoji = "\240\159\135\178\240\159\135\178", 
        Name = "Myanmar(Burma)"
    }, 
    OM = {
        Emoji = "\240\159\135\180\240\159\135\178", 
        Name = "Oman"
    }, 
    PM = {
        Emoji = "\240\159\135\181\240\159\135\178", 
        Name = "St.Pierre & Miquelon"
    }, 
    HU = {
        Emoji = "\240\159\135\173\240\159\135\186", 
        Name = "Hungary"
    }, 
    SM = {
        Emoji = "\240\159\135\184\240\159\135\178", 
        Name = "SanMarino"
    }, 
    TM = {
        Emoji = "\240\159\135\185\240\159\135\178", 
        Name = "Turkmenistan"
    }, 
    PE = {
        Emoji = "\240\159\135\181\240\159\135\170", 
        Name = "Peru"
    }, 
    ZM = {
        Emoji = "\240\159\135\191\240\159\135\178", 
        Name = "Zambia"
    }, 
    AU = {
        Emoji = "\240\159\135\166\240\159\135\186", 
        Name = "Australia"
    }, 
    GE = {
        Emoji = "\240\159\135\172\240\159\135\170", 
        Name = "Georgia"
    }, 
    IE = {
        Emoji = "\240\159\135\174\240\159\135\170", 
        Name = "Ireland"
    }, 
    JE = {
        Emoji = "\240\159\135\175\240\159\135\170", 
        Name = "Jersey"
    }, 
    AM = {
        Emoji = "\240\159\135\166\240\159\135\178", 
        Name = "Armenia"
    }, 
    BM = {
        Emoji = "\240\159\135\167\240\159\135\178", 
        Name = "Bermuda"
    }, 
    NE = {
        Emoji = "\240\159\135\179\240\159\135\170", 
        Name = "Niger"
    }, 
    HM = {
        Emoji = "\240\159\135\173\240\159\135\178", 
        Name = "Heard & McDonaldIslands"
    }, 
    IM = {
        Emoji = "\240\159\135\174\240\159\135\178", 
        Name = "IsleofMan"
    }, 
    ER = {
        Emoji = "\240\159\135\170\240\159\135\183", 
        Name = "Eritrea"
    }, 
    BZ = {
        Emoji = "\240\159\135\167\240\159\135\191", 
        Name = "Belize"
    }, 
    RU = {
        Emoji = "\240\159\135\183\240\159\135\186", 
        Name = "Russia"
    }, 
    NL = {
        Emoji = "\240\159\135\179\240\159\135\177", 
        Name = "Netherlands"
    }, 
    ML = {
        Emoji = "\240\159\135\178\240\159\135\177", 
        Name = "Mali"
    }, 
    MU = {
        Emoji = "\240\159\135\178\240\159\135\186", 
        Name = "Mauritius"
    }, 
    TL = {
        Emoji = "\240\159\135\185\240\159\135\177", 
        Name = "Timor-Leste"
    }, 
    IN = {
        Emoji = "\240\159\135\174\240\159\135\179", 
        Name = "India"
    }, 
    UA = {
        Emoji = "\240\159\135\186\240\159\135\166", 
        Name = "Ukraine"
    }, 
    TD = {
        Emoji = "\240\159\135\185\240\159\135\169", 
        Name = "Chad"
    }, 
    SD = {
        Emoji = "\240\159\135\184\240\159\135\169", 
        Name = "Sudan"
    }, 
    AT = {
        Emoji = "\240\159\135\166\240\159\135\185", 
        Name = "Austria"
    }, 
    TT = {
        Emoji = "\240\159\135\185\240\159\135\185", 
        Name = "Trinidad & Tobago"
    }, 
    ST = {
        Emoji = "\240\159\135\184\240\159\135\185", 
        Name = "S\195\163oTom\195\169 & Pr\195\173ncipe"
    }, 
    MD = {
        Emoji = "\240\159\135\178\240\159\135\169", 
        Name = "Moldova"
    }, 
    AL = {
        Emoji = "\240\159\135\166\240\159\135\177", 
        Name = "Albania"
    }, 
    CM = {
        Emoji = "\240\159\135\168\240\159\135\178", 
        Name = "Cameroon"
    }, 
    BB = {
        Emoji = "\240\159\135\167\240\159\135\167", 
        Name = "Barbados"
    }, 
    BD = {
        Emoji = "\240\159\135\167\240\159\135\169", 
        Name = "Bangladesh"
    }, 
    MZ = {
        Emoji = "\240\159\135\178\240\159\135\191", 
        Name = "Mozambique"
    }, 
    AD = {
        Emoji = "\240\159\135\166\240\159\135\169", 
        Name = "Andorra"
    }, 
    PT = {
        Emoji = "\240\159\135\181\240\159\135\185", 
        Name = "Portugal"
    }, 
    IL = {
        Emoji = "\240\159\135\174\240\159\135\177", 
        Name = "Israel"
    }, 
    ME = {
        Emoji = "\240\159\135\178\240\159\135\170", 
        Name = "Montenegro"
    }, 
    SZ = {
        Emoji = "\240\159\135\184\240\159\135\191", 
        Name = "Swaziland"
    }, 
    VG = {
        Emoji = "\240\159\135\187\240\159\135\172", 
        Name = "BritishVirginIslands"
    }, 
    KR = {
        Emoji = "\240\159\135\176\240\159\135\183", 
        Name = "SouthKorea"
    }, 
    LU = {
        Emoji = "\240\159\135\177\240\159\135\186", 
        Name = "Luxembourg"
    }, 
    MO = {
        Emoji = "\240\159\135\178\240\159\135\180", 
        Name = "MacauSARChina"
    }, 
    NO = {
        Emoji = "\240\159\135\179\240\159\135\180", 
        Name = "Norway"
    }, 
    SO = {
        Emoji = "\240\159\135\184\240\159\135\180", 
        Name = "Somalia"
    }, 
    DM = {
        Emoji = "\240\159\135\169\240\159\135\178", 
        Name = "Dominica"
    }, 
    DO = {
        Emoji = "\240\159\135\169\240\159\135\180", 
        Name = "DominicanRepublic"
    }, 
    VE = {
        Emoji = "\240\159\135\187\240\159\135\170", 
        Name = "Venezuela"
    }, 
    GL = {
        Emoji = "\240\159\135\172\240\159\135\177", 
        Name = "Greenland"
    }, 
    BW = {
        Emoji = "\240\159\135\167\240\159\135\188", 
        Name = "Botswana"
    }, 
    GG = {
        Emoji = "\240\159\135\172\240\159\135\172", 
        Name = "Guernsey"
    }, 
    MG = {
        Emoji = "\240\159\135\178\240\159\135\172", 
        Name = "Madagascar"
    }, 
    NG = {
        Emoji = "\240\159\135\179\240\159\135\172", 
        Name = "Nigeria"
    }, 
    KG = {
        Emoji = "\240\159\135\176\240\159\135\172", 
        Name = "Kyrgyzstan"
    }, 
    FO = {
        Emoji = "\240\159\135\171\240\159\135\180", 
        Name = "FaroeIslands"
    }, 
    MK = {
        Emoji = "\240\159\135\178\240\159\135\176", 
        Name = "Macedonia"
    }, 
    EG = {
        Emoji = "\240\159\135\170\240\159\135\172", 
        Name = "Egypt"
    }, 
    CW = {
        Emoji = "\240\159\135\168\240\159\135\188", 
        Name = "Cura\195\167ao"
    }, 
    CV = {
        Emoji = "\240\159\135\168\240\159\135\187", 
        Name = "CapeVerde"
    }, 
    TN = {
        Emoji = "\240\159\135\185\240\159\135\179", 
        Name = "Tunisia"
    }, 
    AX = {
        Emoji = "\240\159\135\166\240\159\135\189", 
        Name = "\195\133landIslands"
    }, 
    TF = {
        Emoji = "\240\159\135\185\240\159\135\171", 
        Name = "FrenchSouthernTerritories"
    }, 
    GR = {
        Emoji = "\240\159\135\172\240\159\135\183", 
        Name = "Greece"
    }, 
    TH = {
        Emoji = "\240\159\135\185\240\159\135\173", 
        Name = "Thailand"
    }, 
    RS = {
        Emoji = "\240\159\135\183\240\159\135\184", 
        Name = "Serbia"
    }, 
    TV = {
        Emoji = "\240\159\135\185\240\159\135\187", 
        Name = "Tuvalu"
    }, 
    SV = {
        Emoji = "\240\159\135\184\240\159\135\187", 
        Name = "ElSalvador"
    }, 
    BO = {
        Emoji = "\240\159\135\167\240\159\135\180", 
        Name = "Bolivia"
    }, 
    CN = {
        Emoji = "\240\159\135\168\240\159\135\179", 
        Name = "China"
    }, 
    BN = {
        Emoji = "\240\159\135\167\240\159\135\179", 
        Name = "Brunei"
    }, 
    UG = {
        Emoji = "\240\159\135\186\240\159\135\172", 
        Name = "Uganda"
    }, 
    JO = {
        Emoji = "\240\159\135\175\240\159\135\180", 
        Name = "Jordan"
    }, 
    GU = {
        Emoji = "\240\159\135\172\240\159\135\186", 
        Name = "Guam"
    }, 
    LB = {
        Emoji = "\240\159\135\177\240\159\135\167", 
        Name = "Lebanon"
    }, 
    AW = {
        Emoji = "\240\159\135\166\240\159\135\188", 
        Name = "Aruba"
    }, 
    BF = {
        Emoji = "\240\159\135\167\240\159\135\171", 
        Name = "BurkinaFaso"
    }, 
    RW = {
        Emoji = "\240\159\135\183\240\159\135\188", 
        Name = "Rwanda"
    }, 
    KW = {
        Emoji = "\240\159\135\176\240\159\135\188", 
        Name = "Kuwait"
    }, 
    SG = {
        Emoji = "\240\159\135\184\240\159\135\172", 
        Name = "Singapore"
    }, 
    AF = {
        Emoji = "\240\159\135\166\240\159\135\171", 
        Name = "Afghanistan"
    }, 
    YE = {
        Emoji = "\240\159\135\190\240\159\135\170", 
        Name = "Yemen"
    }, 
    CG = {
        Emoji = "\240\159\135\168\240\159\135\172", 
        Name = "Congo-Brazzaville"
    }, 
    CK = {
        Emoji = "\240\159\135\168\240\159\135\176", 
        Name = "CookIslands"
    }, 
    IQ = {
        Emoji = "\240\159\135\174\240\159\135\182", 
        Name = "Iraq"
    }, 
    FJ = {
        Emoji = "\240\159\135\171\240\159\135\175", 
        Name = "Fiji"
    }, 
    PF = {
        Emoji = "\240\159\135\181\240\159\135\171", 
        Name = "FrenchPolynesia"
    }, 
    SN = {
        Emoji = "\240\159\135\184\240\159\135\179", 
        Name = "Senegal"
    }, 
    BV = {
        Emoji = "\240\159\135\167\240\159\135\187", 
        Name = "BouvetIsland"
    }, 
    DE = {
        Emoji = "\240\159\135\169\240\159\135\170", 
        Name = "Germany"
    }, 
    NI = {
        Emoji = "\240\159\135\179\240\159\135\174", 
        Name = "Nicaragua"
    }, 
    QA = {
        Emoji = "\240\159\135\182\240\159\135\166", 
        Name = "Qatar"
    }, 
    ZA = {
        Emoji = "\240\159\135\191\240\159\135\166", 
        Name = "SouthAfrica"
    }, 
    CY = {
        Emoji = "\240\159\135\168\240\159\135\190", 
        Name = "Cyprus"
    }, 
    MF = {
        Emoji = "\240\159\135\178\240\159\135\171", 
        Name = "St.Martin"
    }, 
    CI = {
        Emoji = "\240\159\135\168\240\159\135\174", 
        Name = "C\195\180ted\226\128\153Ivoire"
    }, 
    NA = {
        Emoji = "\240\159\135\179\240\159\135\166", 
        Name = "Namibia"
    }, 
    NU = {
        Emoji = "\240\159\135\179\240\159\135\186", 
        Name = "Niue"
    }, 
    IO = {
        Emoji = "\240\159\135\174\240\159\135\180", 
        Name = "BritishIndianOceanTerritory"
    }, 
    KZ = {
        Emoji = "\240\159\135\176\240\159\135\191", 
        Name = "Kazakhstan"
    }, 
    LY = {
        Emoji = "\240\159\135\177\240\159\135\190", 
        Name = "Libya"
    }, 
    MY = {
        Emoji = "\240\159\135\178\240\159\135\190", 
        Name = "Malaysia"
    }, 
    BY = {
        Emoji = "\240\159\135\167\240\159\135\190", 
        Name = "Belarus"
    }, 
    RO = {
        Emoji = "\240\159\135\183\240\159\135\180", 
        Name = "Romania"
    }, 
    VC = {
        Emoji = "\240\159\135\187\240\159\135\168", 
        Name = "St.Vincent & Grenadines"
    }, 
    BQ = {
        Emoji = "\240\159\135\167\240\159\135\182", 
        Name = "CaribbeanNetherlands"
    }, 
    DJ = {
        Emoji = "\240\159\135\169\240\159\135\175", 
        Name = "Djibouti"
    }, 
    TO = {
        Emoji = "\240\159\135\185\240\159\135\180", 
        Name = "Tonga"
    }, 
    AI = {
        Emoji = "\240\159\135\166\240\159\135\174", 
        Name = "Anguilla"
    }, 
    CZ = {
        Emoji = "\240\159\135\168\240\159\135\191", 
        Name = "Czechia"
    }, 
    MT = {
        Emoji = "\240\159\135\178\240\159\135\185", 
        Name = "Malta"
    }, 
    GA = {
        Emoji = "\240\159\135\172\240\159\135\166", 
        Name = "Gabon"
    }, 
    FR = {
        Emoji = "\240\159\135\171\240\159\135\183", 
        Name = "France"
    }, 
    TZ = {
        Emoji = "\240\159\135\185\240\159\135\191", 
        Name = "Tanzania"
    }, 
    UM = {
        Emoji = "\240\159\135\186\240\159\135\178", 
        Name = "U.S.OutlyingIslands"
    }, 
    FI = {
        Emoji = "\240\159\135\171\240\159\135\174", 
        Name = "Finland"
    }, 
    LI = {
        Emoji = "\240\159\135\177\240\159\135\174", 
        Name = "Liechtenstein"
    }, 
    JP = {
        Emoji = "\240\159\135\175\240\159\135\181", 
        Name = "Japan"
    }, 
    PW = {
        Emoji = "\240\159\135\181\240\159\135\188", 
        Name = "Palau"
    }, 
    PH = {
        Emoji = "\240\159\135\181\240\159\135\173", 
        Name = "Philippines"
    }, 
    MQ = {
        Emoji = "\240\159\135\178\240\159\135\182", 
        Name = "Martinique"
    }, 
    GW = {
        Emoji = "\240\159\135\172\240\159\135\188", 
        Name = "Guinea-Bissau"
    }, 
    TG = {
        Emoji = "\240\159\135\185\240\159\135\172", 
        Name = "Togo"
    }, 
    NF = {
        Emoji = "\240\159\135\179\240\159\135\171", 
        Name = "NorfolkIsland"
    }, 
    JM = {
        Emoji = "\240\159\135\175\240\159\135\178", 
        Name = "Jamaica"
    }, 
    HT = {
        Emoji = "\240\159\135\173\240\159\135\185", 
        Name = "Haiti"
    }, 
    GT = {
        Emoji = "\240\159\135\172\240\159\135\185", 
        Name = "Guatemala"
    }, 
    LV = {
        Emoji = "\240\159\135\177\240\159\135\187", 
        Name = "Latvia"
    }, 
    ZW = {
        Emoji = "\240\159\135\191\240\159\135\188", 
        Name = "Zimbabwe"
    }, 
    CU = {
        Emoji = "\240\159\135\168\240\159\135\186", 
        Name = "Cuba"
    }, 
    LR = {
        Emoji = "\240\159\135\177\240\159\135\183", 
        Name = "Liberia"
    }, 
    SH = {
        Emoji = "\240\159\135\184\240\159\135\173", 
        Name = "St.Helena"
    }, 
    KI = {
        Emoji = "\240\159\135\176\240\159\135\174", 
        Name = "Kiribati"
    }, 
    RE = {
        Emoji = "\240\159\135\183\240\159\135\170", 
        Name = "R\195\169union"
    }, 
    CX = {
        Emoji = "\240\159\135\168\240\159\135\189", 
        Name = "ChristmasIsland"
    }, 
    WF = {
        Emoji = "\240\159\135\188\240\159\135\171", 
        Name = "Wallis & Futuna"
    }, 
    SA = {
        Emoji = "\240\159\135\184\240\159\135\166", 
        Name = "SaudiArabia"
    }, 
    HN = {
        Emoji = "\240\159\135\173\240\159\135\179", 
        Name = "Honduras"
    }, 
    VN = {
        Emoji = "\240\159\135\187\240\159\135\179", 
        Name = "Vietnam"
    }, 
    CH = {
        Emoji = "\240\159\135\168\240\159\135\173", 
        Name = "Switzerland"
    }, 
    BT = {
        Emoji = "\240\159\135\167\240\159\135\185", 
        Name = "Bhutan"
    }, 
    EH = {
        Emoji = "\240\159\135\170\240\159\135\173", 
        Name = "WesternSahara"
    }, 
    TW = {
        Emoji = "\240\159\135\185\240\159\135\188", 
        Name = "Taiwan"
    }, 
    GD = {
        Emoji = "\240\159\135\172\240\159\135\169", 
        Name = "Grenada"
    }, 
    KH = {
        Emoji = "\240\159\135\176\240\159\135\173", 
        Name = "Cambodia"
    }, 
    BA = {
        Emoji = "\240\159\135\167\240\159\135\166", 
        Name = "Bosnia & Herzegovina"
    }, 
    VA = {
        Emoji = "\240\159\135\187\240\159\135\166", 
        Name = "VaticanCity"
    }, 
    MA = {
        Emoji = "\240\159\135\178\240\159\135\166", 
        Name = "Morocco"
    }, 
    GP = {
        Emoji = "\240\159\135\172\240\159\135\181", 
        Name = "Guadeloupe"
    }, 
    BL = {
        Emoji = "\240\159\135\167\240\159\135\177", 
        Name = "St.Barth\195\169lemy"
    }, 
    GY = {
        Emoji = "\240\159\135\172\240\159\135\190", 
        Name = "Guyana"
    }, 
    TK = {
        Emoji = "\240\159\135\185\240\159\135\176", 
        Name = "Tokelau"
    }, 
    MH = {
        Emoji = "\240\159\135\178\240\159\135\173", 
        Name = "MarshallIslands"
    }, 
    SR = {
        Emoji = "\240\159\135\184\240\159\135\183", 
        Name = "Suriname"
    }, 
    AE = {
        Emoji = "\240\159\135\166\240\159\135\170", 
        Name = "UnitedArabEmirates"
    }, 
    KP = {
        Emoji = "\240\159\135\176\240\159\135\181", 
        Name = "NorthKorea"
    }, 
    GN = {
        Emoji = "\240\159\135\172\240\159\135\179", 
        Name = "Guinea"
    }, 
    GB = {
        Emoji = "\240\159\135\172\240\159\135\167", 
        Name = "UnitedKingdom"
    }, 
    GH = {
        Emoji = "\240\159\135\172\240\159\135\173", 
        Name = "Ghana"
    }, 
    UY = {
        Emoji = "\240\159\135\186\240\159\135\190", 
        Name = "Uruguay"
    }, 
    SL = {
        Emoji = "\240\159\135\184\240\159\135\177", 
        Name = "SierraLeone"
    }, 
    SJ = {
        Emoji = "\240\159\135\184\240\159\135\175", 
        Name = "Svalbard & JanMayen"
    }, 
    IS = {
        Emoji = "\240\159\135\174\240\159\135\184", 
        Name = "Iceland"
    }, 
    PN = {
        Emoji = "\240\159\135\181\240\159\135\179", 
        Name = "PitcairnIslands"
    }, 
    YT = {
        Emoji = "\240\159\135\190\240\159\135\185", 
        Name = "Mayotte"
    }, 
    FM = {
        Emoji = "\240\159\135\171\240\159\135\178", 
        Name = "Micronesia"
    }, 
    AZ = {
        Emoji = "\240\159\135\166\240\159\135\191", 
        Name = "Azerbaijan"
    }, 
    GI = {
        Emoji = "\240\159\135\172\240\159\135\174", 
        Name = "Gibraltar"
    }, 
    CF = {
        Emoji = "\240\159\135\168\240\159\135\171", 
        Name = "CentralAfricanRepublic"
    }, 
    PK = {
        Emoji = "\240\159\135\181\240\159\135\176", 
        Name = "Pakistan"
    }, 
    SE = {
        Emoji = "\240\159\135\184\240\159\135\170", 
        Name = "Sweden"
    }, 
    CL = {
        Emoji = "\240\159\135\168\240\159\135\177", 
        Name = "Chile"
    }, 
    FK = {
        Emoji = "\240\159\135\171\240\159\135\176", 
        Name = "FalklandIslands"
    }, 
    MW = {
        Emoji = "\240\159\135\178\240\159\135\188", 
        Name = "Malawi"
    }, 
    GM = {
        Emoji = "\240\159\135\172\240\159\135\178", 
        Name = "Gambia"
    }, 
    SK = {
        Emoji = "\240\159\135\184\240\159\135\176", 
        Name = "Slovakia"
    }, 
    GS = {
        Emoji = "\240\159\135\172\240\159\135\184", 
        Name = "SouthGeorgia & SouthSandwichIslands"
    }, 
    MV = {
        Emoji = "\240\159\135\178\240\159\135\187", 
        Name = "Maldives"
    }, 
    IT = {
        Emoji = "\240\159\135\174\240\159\135\185", 
        Name = "Italy"
    }, 
    PY = {
        Emoji = "\240\159\135\181\240\159\135\190", 
        Name = "Paraguay"
    }, 
    ES = {
        Emoji = "\240\159\135\170\240\159\135\184", 
        Name = "Spain"
    }, 
    NR = {
        Emoji = "\240\159\135\179\240\159\135\183", 
        Name = "Nauru"
    }, 
    GQ = {
        Emoji = "\240\159\135\172\240\159\135\182", 
        Name = "EquatorialGuinea"
    }, 
    MN = {
        Emoji = "\240\159\135\178\240\159\135\179", 
        Name = "Mongolia"
    }, 
    PL = {
        Emoji = "\240\159\135\181\240\159\135\177", 
        Name = "Poland"
    }, 
    SC = {
        Emoji = "\240\159\135\184\240\159\135\168", 
        Name = "Seychelles"
    }, 
    PG = {
        Emoji = "\240\159\135\181\240\159\135\172", 
        Name = "PapuaNewGuinea"
    }, 
    AQ = {
        Emoji = "\240\159\135\166\240\159\135\182", 
        Name = "Antarctica"
    }, 
    BG = {
        Emoji = "\240\159\135\167\240\159\135\172", 
        Name = "Bulgaria"
    }, 
    TC = {
        Emoji = "\240\159\135\185\240\159\135\168", 
        Name = "Turks & CaicosIslands"
    }, 
    VU = {
        Emoji = "\240\159\135\187\240\159\135\186", 
        Name = "Vanuatu"
    }, 
    MP = {
        Emoji = "\240\159\135\178\240\159\135\181", 
        Name = "NorthernMarianaIslands"
    }, 
    BI = {
        Emoji = "\240\159\135\167\240\159\135\174", 
        Name = "Burundi"
    }, 
    AR = {
        Emoji = "\240\159\135\166\240\159\135\183", 
        Name = "Argentina"
    }, 
    LT = {
        Emoji = "\240\159\135\177\240\159\135\185", 
        Name = "Lithuania"
    }, 
    AO = {
        Emoji = "\240\159\135\166\240\159\135\180", 
        Name = "Angola"
    }, 
    NP = {
        Emoji = "\240\159\135\179\240\159\135\181", 
        Name = "Nepal"
    }, 
    DK = {
        Emoji = "\240\159\135\169\240\159\135\176", 
        Name = "Denmark"
    }, 
    KY = {
        Emoji = "\240\159\135\176\240\159\135\190", 
        Name = "CaymanIslands"
    }, 
    CD = {
        Emoji = "\240\159\135\168\240\159\135\169", 
        Name = "Congo-Kinshasa"
    }, 
    EE = {
        Emoji = "\240\159\135\170\240\159\135\170", 
        Name = "Estonia"
    }, 
    CA = {
        Emoji = "\240\159\135\168\240\159\135\166", 
        Name = "Canada"
    }, 
    MC = {
        Emoji = "\240\159\135\178\240\159\135\168", 
        Name = "Monaco"
    }, 
    NZ = {
        Emoji = "\240\159\135\179\240\159\135\191", 
        Name = "NewZealand"
    }, 
    KN = {
        Emoji = "\240\159\135\176\240\159\135\179", 
        Name = "St.Kitts & Nevis"
    }, 
    DZ = {
        Emoji = "\240\159\135\169\240\159\135\191", 
        Name = "Algeria"
    }, 
    WS = {
        Emoji = "\240\159\135\188\240\159\135\184", 
        Name = "Samoa"
    }, 
    NC = {
        Emoji = "\240\159\135\179\240\159\135\168", 
        Name = "NewCaledonia"
    }, 
    GF = {
        Emoji = "\240\159\135\172\240\159\135\171", 
        Name = "FrenchGuiana"
    }, 
    PA = {
        Emoji = "\240\159\135\181\240\159\135\166", 
        Name = "Panama"
    }, 
    BH = {
        Emoji = "\240\159\135\167\240\159\135\173", 
        Name = "Bahrain"
    }, 
    PS = {
        Emoji = "\240\159\135\181\240\159\135\184", 
        Name = "PalestinianTerritories"
    }, 
    HK = {
        Emoji = "\240\159\135\173\240\159\135\176", 
        Name = "HongKongSARChina"
    }, 
    SI = {
        Emoji = "\240\159\135\184\240\159\135\174", 
        Name = "Slovenia"
    }, 
    LK = {
        Emoji = "\240\159\135\177\240\159\135\176", 
        Name = "SriLanka"
    }, 
    SS = {
        Emoji = "\240\159\135\184\240\159\135\184", 
        Name = "SouthSudan"
    }, 
    CC = {
        Emoji = "\240\159\135\168\240\159\135\168", 
        Name = "Cocos(Keeling)Islands"
    }, 
    US = {
        Emoji = "\240\159\135\186\240\159\135\184", 
        Name = "UnitedStates"
    }, 
    EC = {
        Emoji = "\240\159\135\170\240\159\135\168", 
        Name = "Ecuador"
    }, 
    SY = {
        Emoji = "\240\159\135\184\240\159\135\190", 
        Name = "Syria"
    }, 
    IR = {
        Emoji = "\240\159\135\174\240\159\135\183", 
        Name = "Iran"
    }, 
    BE = {
        Emoji = "\240\159\135\167\240\159\135\170", 
        Name = "Belgium"
    }, 
    AG = {
        Emoji = "\240\159\135\166\240\159\135\172", 
        Name = "Antigua & Barbuda"
    }, 
    LS = {
        Emoji = "\240\159\135\177\240\159\135\184", 
        Name = "Lesotho"
    }, 
    MS = {
        Emoji = "\240\159\135\178\240\159\135\184", 
        Name = "Montserrat"
    }, 
    BS = {
        Emoji = "\240\159\135\167\240\159\135\184", 
        Name = "Bahamas"
    }, 
    SX = {
        Emoji = "\240\159\135\184\240\159\135\189", 
        Name = "SintMaarten"
    }, 
    KM = {
        Emoji = "\240\159\135\176\240\159\135\178", 
        Name = "Comoros"
    }, 
    LA = {
        Emoji = "\240\159\135\177\240\159\135\166", 
        Name = "Laos"
    }, 
    ID = {
        Emoji = "\240\159\135\174\240\159\135\169", 
        Name = "Indonesia"
    }, 
    CO = {
        Emoji = "\240\159\135\168\240\159\135\180", 
        Name = "Colombia"
    }, 
    MX = {
        Emoji = "\240\159\135\178\240\159\135\189", 
        Name = "Mexico"
    }, 
    ET = {
        Emoji = "\240\159\135\170\240\159\135\185", 
        Name = "Ethiopia"
    }, 
    LC = {
        Emoji = "\240\159\135\177\240\159\135\168", 
        Name = "St.Lucia"
    }, 
    VI = {
        Emoji = "\240\159\135\187\240\159\135\174", 
        Name = "U.S.VirginIslands"
    }, 
    AS = {
        Emoji = "\240\159\135\166\240\159\135\184", 
        Name = "AmericanSamoa"
    }
};