return {
    ["Festive Dog"] = {
        Image = "rbxassetid://79967494322744", 
        Multiplier1 = 40000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Festive Cat"] = {
        Image = "rbxassetid://76729969564215", 
        Multiplier1 = 45000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Festive Bunny"] = {
        Image = "rbxassetid://95483009855609", 
        Multiplier1 = 55000, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    ["Festive Penguin"] = {
        Image = "rbxassetid://131412266605374", 
        Multiplier1 = 85000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Walking"
    }, 
    ["5M Snowglobe"] = {
        Image = "rbxassetid://113057125147416", 
        Multiplier1 = 100000, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Walking"
    }, 
    ["Gingerbread Dragon"] = {
        Image = "rbxassetid://102100694016152", 
        Multiplier1 = 200000, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Walking"
    }, 
    ["Frosty Snowman"] = {
        Image = "rbxassetid://132343928972208", 
        Multiplier1 = 350000, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        InfoText = "1 in 150,000", 
        BigFrame = true
    }, 
    ["5M North Star"] = {
        Image = "rbxassetid://100379557578255", 
        Multiplier1 = 500000, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        InfoText = "1 in 500,000", 
        BigFrame = true
    }, 
    ["5M Frost Monarch"] = {
        Image = "rbxassetid://72244261442408", 
        Multiplier1 = 1000000, 
        Multiplier2 = 0, 
        Rarity = "Secret II", 
        Movement = "Flying", 
        InfoText = "1 in 1,500,000", 
        BigFrame = true
    }, 
    Snowboo = {
        Image = "rbxassetid://85443408714245", 
        Multiplier1 = 50000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Santa Bear"] = {
        Image = "rbxassetid://134182774839933", 
        Multiplier1 = 56000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Rudolph = {
        Image = "rbxassetid://88962037267495", 
        Multiplier1 = 70000, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    ["Festive Owl"] = {
        Image = "rbxassetid://104130022606335", 
        Multiplier1 = 100000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    Ornament = {
        Image = "rbxassetid://115032422895128", 
        Multiplier1 = 125000, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    Nutcracker = {
        Image = "rbxassetid://77579599750572", 
        Multiplier1 = 250000, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Flying"
    }, 
    ["Frost Spirit"] = {
        Image = "rbxassetid://128408846481902", 
        Multiplier1 = 625000, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        InfoText = "1 in 250,000", 
        BigFrame = true
    }, 
    ["Christmas Tree"] = {
        Image = "rbxassetid://105644631296243", 
        Multiplier1 = 875000, 
        Multiplier2 = 1.5, 
        Rarity = "Secret II", 
        Movement = "Flying", 
        InfoText = "1 in 500,000", 
        BigFrame = true
    }, 
    ["Gilded Seraphim"] = {
        Image = "rbxassetid://74934057909888", 
        Multiplier1 = 3000000, 
        Multiplier2 = 1.5, 
        Rarity = "Secret II", 
        Movement = "Flying", 
        InfoText = "1 in 1,750,000", 
        BigFrame = true
    }, 
    ["Party Puppy"] = {
        Image = "rbxassetid://93590593621455", 
        Multiplier1 = 90000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Party Cat"] = {
        Image = "rbxassetid://140589890514933", 
        Multiplier1 = 100000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Sprinkler Bunny"] = {
        Image = "rbxassetid://96189152739494", 
        Multiplier1 = 140000, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Firework = {
        Image = "rbxassetid://71958406916874", 
        Multiplier1 = 180000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Mr Sprinkler"] = {
        Image = "rbxassetid://112776197309312", 
        Multiplier1 = 220000, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    ["Starshine Warrior"] = {
        Image = "rbxassetid://117619291731509", 
        Multiplier1 = 580000, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Flying"
    }, 
    ["2026 Balloons"] = {
        Image = "rbxassetid://75772902548670", 
        Multiplier1 = 2300000, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        InfoText = "1 in 500,000", 
        BigFrame = true
    }, 
    ["New Year Dragon"] = {
        Image = "rbxassetid://70970191445717", 
        Multiplier1 = 4850000, 
        Multiplier2 = 1.5, 
        Rarity = "Secret II", 
        Movement = "Flying", 
        InfoText = "1 in 1,000,000", 
        BigFrame = true
    }, 
    ["2026 Overlord"] = {
        Image = "rbxassetid://136279249697972", 
        Multiplier1 = 8500000, 
        Multiplier2 = 1.5, 
        Rarity = "Secret II", 
        Movement = "Flying", 
        InfoText = "1 in 2,500,000", 
        BigFrame = true
    }, 
    ["Mistletoe Wyvern"] = {
        Image = "rbxassetid://73678347460852", 
        Image_Golden = "rbxassetid://73678347460852", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 110, 
        InfoText = "SECRET BUNDLE", 
        BigFrame = true, 
        Rarity = "Secret II", 
        Movement = "Walking"
    }, 
    ["2026 Star"] = {
        Image = "rbxassetid://119567529624252", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 115, 
        InfoText = "SECRET PACK", 
        BigFrame = true, 
        Rarity = "Secret II", 
        Movement = "Walking"
    }, 
    ["Celestial Candycane"] = {
        Image = "rbxassetid://132808110783176", 
        Image_Golden = "rbxassetid://132808110783176", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 115, 
        InfoText = "SECRET BUNDLE", 
        BigFrame = true, 
        Rarity = "Secret II", 
        Movement = "Walking"
    }, 
    ["Disco Lord"] = {
        Image = "rbxassetid://129277024342539", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 110, 
        InfoText = "2026", 
        BigFrame = true, 
        Rarity = "Secret II", 
        Movement = "Walking"
    }, 
    ["Magma Imp"] = {
        Image = "rbxassetid://95292109356234", 
        Multiplier1 = 15000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Magmatic Angel"] = {
        Image = "rbxassetid://70994218309064", 
        Multiplier1 = 18000, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Flying"
    }, 
    ["Magma Wyvern"] = {
        Image = "rbxassetid://105988748644637", 
        Multiplier1 = 24000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Lava God"] = {
        Image = "rbxassetid://131943299758956", 
        Multiplier1 = 35000, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    ["Frozen Yeti"] = {
        Image = "rbxassetid://130462336628267", 
        Multiplier1 = 300, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Frost Wolf"] = {
        Image = "rbxassetid://128836505243656", 
        Multiplier1 = 400, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    ["Ice Crystal Demon"] = {
        Image = "rbxassetid://106855739227211", 
        Multiplier1 = 500, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Tundra God"] = {
        Image = "rbxassetid://133395922286215", 
        Multiplier1 = 600, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    ["Dusty Wolf"] = {
        Image = "rbxassetid://91614089488201", 
        Multiplier1 = 500, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Arid Goat"] = {
        Image = "rbxassetid://73470009770009", 
        Multiplier1 = 550, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Aurelin = {
        Image = "rbxassetid://103351330498563", 
        Multiplier1 = 600, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    Seraphlux = {
        Image = "rbxassetid://103406070099666", 
        Multiplier1 = 700, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    Sproutling = {
        Image = "rbxassetid://140344489686997", 
        Multiplier1 = 800, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Tigerclaw = {
        Image = "rbxassetid://71980482334121", 
        Multiplier1 = 900, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Emberagon = {
        Image = "rbxassetid://138910730990678", 
        Multiplier1 = 1000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    Voltgryph = {
        Image = "rbxassetid://83718237615127", 
        Multiplier1 = 1100, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    Serapha = {
        Image = "rbxassetid://81741135232144", 
        Multiplier1 = 1200, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Flying"
    }, 
    Voidling = {
        Image = "rbxassetid://89750757074441", 
        Multiplier1 = 1300, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Blink = {
        Image = "rbxassetid://131811938233117", 
        Multiplier1 = 1400, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    Aetherfin = {
        Image = "rbxassetid://97489682483367", 
        Multiplier1 = 1500, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    Samuwai = {
        Image = "rbxassetid://129232356571292", 
        Multiplier1 = 15000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Bloodfrost = {
        Image = "rbxassetid://91952140893191", 
        Multiplier1 = 18000, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Ashfiend = {
        Image = "rbxassetid://78985865207612", 
        Multiplier1 = 24000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    Bladekaiser = {
        Image = "rbxassetid://115156114648234", 
        Multiplier1 = 35000, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    ["Social Dragon"] = {
        Image = "rbxassetid://79500464776302", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 60, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    ["Trophy Guardian"] = {
        Image = "rbxassetid://94245162952036", 
        Image_Golden = "rbxassetid://94245162952036", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 90, 
        Rarity = "Leaderboard", 
        InfoText = "Top 250", 
        Movement = "Flying"
    }, 
    ["Silver Emperor"] = {
        Image = "rbxassetid://119856023384874", 
        Image_Golden = "rbxassetid://119856023384874", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 110, 
        Rarity = "Leaderboard", 
        Movement = "Flying", 
        InfoText = "Top 100", 
        BigFrame = true
    }, 
    ["Divine Celestia"] = {
        Image = "rbxassetid://70425320787678", 
        Image_Golden = "rbxassetid://70425320787678", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 125, 
        Rarity = "Leaderboard", 
        Movement = "Flying", 
        InfoText = "Top 10", 
        BigFrame = true
    }, 
    ["Frost Warrior"] = {
        Image = "rbxassetid://129949865867820", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 90, 
        Rarity = "Leaderboard", 
        InfoText = "Top 250", 
        Movement = "Flying"
    }, 
    ["Snow Emperor"] = {
        Image = "rbxassetid://73424918649029", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 110, 
        Rarity = "Leaderboard", 
        Movement = "Flying", 
        InfoText = "Top 100", 
        BigFrame = true
    }, 
    ["Reindeer Emperor"] = {
        Image = "rbxassetid://134098241361994", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 125, 
        Rarity = "Leaderboard", 
        Movement = "Flying", 
        InfoText = "Top 10", 
        BigFrame = true
    }, 
    ["Neon Cat"] = {
        Image = "rbxassetid://71588280927713", 
        Image_Golden = "rbxassetid://71588280927713", 
        Multiplier1 = 5000, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Walking", 
        BigFrame = true
    }, 
    Chronos = {
        Image = "rbxassetid://102623615952068", 
        Image_Golden = "rbxassetid://102623615952068", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 100, 
        Rarity = "Secret I", 
        Movement = "Walking", 
        InfoText = "1 in 1,000", 
        BigFrame = true
    }, 
    Paradox = {
        Image = "rbxassetid://92425515582082", 
        Image_Golden = "rbxassetid://92425515582082", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 85, 
        Rarity = "Mythical", 
        Movement = "Walking"
    }, 
    Kairos = {
        Image = "rbxassetid://131661232260627", 
        Image_Golden = "rbxassetid://131661232260627", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 75, 
        Rarity = "Legendary", 
        Movement = "Walking"
    }, 
    ["Amethyst Hawk"] = {
        Image = "rbxassetid://74407744064142", 
        Image_Golden = "rbxassetid://13363642714", 
        Multiplier1 = 200, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Walking"
    }, 
    ["Christmas Goat"] = {
        Image = "rbxassetid://97361174418005", 
        Image_Golden = "rbxassetid://97361174418005", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 70, 
        Rarity = "Legendary", 
        Movement = "Walking"
    }, 
    ["Gift Mimic"] = {
        Image = "rbxassetid://119252736426802", 
        Image_Golden = "rbxassetid://119252736426802", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 75, 
        Rarity = "Legendary", 
        Movement = "Walking"
    }, 
    ["Snow Thief"] = {
        Image = "rbxassetid://131154503761742", 
        Image_Golden = "rbxassetid://131154503761742", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 80, 
        Rarity = "Legendary", 
        Movement = "Walking"
    }, 
    ["Evil Snowman"] = {
        Image = "rbxassetid://128635238037579", 
        Image_Golden = "rbxassetid://128635238037579", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 90, 
        Rarity = "Mythical", 
        Movement = "Walking"
    }, 
    Krampus = {
        Image = "rbxassetid://137993427163801", 
        Image_Golden = "rbxassetid://137993427163801", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 110, 
        InfoText = "1 in 1,000", 
        BigFrame = true, 
        Rarity = "Secret II", 
        Movement = "Walking"
    }, 
    ["Hooded Krampus"] = {
        Image = "rbxassetid://99008775985281", 
        Image_Golden = "rbxassetid://99008775985281", 
        Multiplier1 = 0, 
        Multiplier2 = 0, 
        Percentage = 90, 
        InfoText = "1 in 1,000", 
        BigFrame = true, 
        Rarity = "Secret I", 
        Movement = "Walking"
    }, 
    Puppy = {
        Image = "rbxassetid://117703968361687|[512, 512]", 
        Image_Golden = "rbxassetid://13363642714", 
        Multiplier1 = 2, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Cat = {
        Image = "rbxassetid://117703968361687|[512, 0]", 
        Image_Golden = "rbxassetid://13363641586", 
        Multiplier1 = 2, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Bunny = {
        Image = "rbxassetid://117703968361687|[256, 0]", 
        Image_Golden = "rbxassetid://13363640774", 
        Multiplier1 = 3, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Bear = {
        Image = "rbxassetid://117703968361687|[0, 0]", 
        Image_Golden = "rbxassetid://13363639405", 
        Multiplier1 = 4, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Panther = {
        Image = "rbxassetid://117703968361687|[256, 512]", 
        Multiplier1 = 6, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Hamster = {
        Image = "rbxassetid://117703968361687|[512, 256]", 
        Multiplier1 = 6, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Mouse = {
        Image = "rbxassetid://117703968361687|[756, 256]", 
        Multiplier1 = 7, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Chicken = {
        Image = "rbxassetid://117703968361687|[768, 0]", 
        Multiplier1 = 8, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Sheep = {
        Image = "rbxassetid://117703968361687|[768, 512]", 
        Image_Golden = "rbxassetid://13363646798", 
        Multiplier1 = 10, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Doggy = {
        Image = "rbxassetid://117703968361687|[0, 256]", 
        Multiplier1 = 12, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Owl = {
        Image = "rbxassetid://117703968361687|[0, 512]", 
        Multiplier1 = 17, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    Boar = {
        Image = "rbxassetid://85561472582312|[0, 0]", 
        Image_Golden = "rbxassetid://13363639757", 
        Multiplier1 = 25, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Zebra = {
        Image = "rbxassetid://12951985116", 
        Multiplier1 = 27, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Elephant = {
        Image = "rbxassetid://117703968361687|[256, 256]", 
        Image_Golden = "rbxassetid://13363643491", 
        Multiplier1 = 30, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Lion = {
        Image = "rbxassetid://85561472582312|[256, 256]", 
        Image_Golden = "rbxassetid://13363644182", 
        Multiplier1 = 33, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Lynx = {
        Image = "rbxassetid://85561472582312|[512, 256]", 
        Multiplier1 = 40, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Walking"
    }, 
    ["Cardinal Hydra"] = {
        Image = "rbxassetid://85561472582312|[256, 0]", 
        Multiplier1 = 75, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    Cottontail = {
        Image = "rbxassetid://91362761774378", 
        Multiplier1 = 40, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Pig = {
        Image = "rbxassetid://87745587487568", 
        Multiplier1 = 43, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Goat = {
        Image = "rbxassetid://85561472582312|[0, 256]", 
        Multiplier1 = 45, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Cow = {
        Image = "rbxassetid://109462370673030", 
        Multiplier1 = 46, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Fox = {
        Image = "rbxassetid://105785517302702", 
        Multiplier1 = 50, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Walking"
    }, 
    Bee = {
        Image = "rbxassetid://81471741190326", 
        Multiplier1 = 70, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Walking"
    }, 
    ["Queen Bee"] = {
        Image = "rbxassetid://115638970958888", 
        Multiplier1 = 120, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Walking"
    }, 
    Moose = {
        Image = "rbxassetid://85561472582312|[0, 512]", 
        Multiplier1 = 50, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Mammoth = {
        Image = "rbxassetid://85561472582312|[768, 256]", 
        Multiplier1 = 60, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Snowman = {
        Multiplier1 = 70, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking", 
        Image = "rbxassetid://101662732894855|[768, 0]"
    }, 
    Yeti = {
        Image = "rbxassetid://85561472582312|[768, 512]", 
        Image_Golden = "rbxassetid://13363648310", 
        Multiplier1 = 85, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    ["Tri-Yeti"] = {
        Image = "rbxassetid://85561472582312|[512, 512]", 
        Multiplier1 = 100, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Walking"
    }, 
    ["Frost Golem"] = {
        Image = "rbxassetid://72696198644317", 
        Multiplier1 = 250, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Walking"
    }, 
    ["Frost Queen"] = {
        Image = "rbxassetid://85561472582312|[768, 0]", 
        Multiplier1 = 3000, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        InfoText = "1 in 100,000", 
        BigFrame = true
    }, 
    ["Dune Dog"] = {
        Image = "rbxassetid://101662732894855|[-1, 255]", 
        Multiplier1 = 125, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Mummy = {
        Image = "rbxassetid://101662732894855|[513, 256]", 
        Multiplier1 = 140, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Camel = {
        Image = "rbxassetid://101662732894855|[256, 0]", 
        Image_Golden = "rbxassetid://13363641176", 
        Multiplier1 = 190, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Mummified Wyvern"] = {
        Image = "rbxassetid://101662732894855|[256, 256]", 
        Multiplier1 = 240, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Flying"
    }, 
    Sphinx = {
        Image = "rbxassetid://101662732894855|[256, 512]", 
        Multiplier1 = 300, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Cactus Raider"] = {
        Image = "rbxassetid://85846591608626", 
        Multiplier1 = 500, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    ["Serpent God"] = {
        Image = "rbxassetid://101662732894855|[0, 512]", 
        Multiplier1 = 760, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Flying"
    }, 
    Frog = {
        Image = "rbxassetid://90762813745343|[0, 0]", 
        Multiplier1 = 320, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Monkey = {
        Image = "rbxassetid://90762813745343|[512, 256]", 
        Image_Golden = "rbxassetid://13363644607", 
        Multiplier1 = 370, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Spider = {
        Image = "rbxassetid://90762813745343|[512, 512]", 
        Image_Golden = "rbxassetid://13363647153", 
        Multiplier1 = 420, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Gorilla = {
        Image = "rbxassetid://90762813745343|[256, 0]", 
        Multiplier1 = 470, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Panda = {
        Image = "rbxassetid://90762813745343|[768, 256]", 
        Multiplier1 = 560, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Walking"
    }, 
    ["Jungle Hydra"] = {
        Image = "rbxassetid://90762813745343|[0, 256]", 
        Multiplier1 = 730, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Venom Dominus"] = {
        Image = "rbxassetid://90762813745343|[256, 768]", 
        Multiplier1 = 950, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    Treant = {
        Image = "rbxassetid://91900473005163", 
        Multiplier1 = 2000, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Flying"
    }, 
    ["Holy Squirrel"] = {
        Image = "rbxassetid://90762813745343|[768, 0]", 
        Multiplier1 = 850, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Halo Chicken"] = {
        Image = "rbxassetid://90762813745343|[512, 0]", 
        Multiplier1 = 900, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Phoenix = {
        Image = "rbxassetid://90762813745343|[0, 512]", 
        Multiplier1 = 1000, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    ["Tri-Phoenix"] = {
        Image = "rbxassetid://90762813745343|[0, 768]", 
        Multiplier1 = 1100, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Tree Of Life"] = {
        Image = "rbxassetid://90762813745343|[768, 512]", 
        Multiplier1 = 1400, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Walking"
    }, 
    ["Divine Guard"] = {
        Image = "rbxassetid://108480874038490", 
        Multiplier1 = 1500, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    Archangel = {
        Image = "rbxassetid://138578173663021", 
        Multiplier1 = 2500, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Flying"
    }, 
    ["Weeping Angel"] = {
        Image = "rbxassetid://132647873582657", 
        Multiplier1 = 6500, 
        Multiplier2 = 1.5, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        InfoText = "1 in 333,333", 
        BigFrame = true
    }, 
    ["Ninja Pup"] = {
        Image = "rbxassetid://98812941218168", 
        Multiplier1 = 2200, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Karate Lynx"] = {
        Image = "rbxassetid://117773878683589", 
        Multiplier1 = 2300, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    ["Sakura Nymph"] = {
        Image = "rbxassetid://117346160400083", 
        Multiplier1 = 2650, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    ["Bonsai Monster"] = {
        Image = "rbxassetid://136816677238440", 
        Multiplier1 = 2900, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Ninja Demon"] = {
        Image = "rbxassetid://127947851664161", 
        Multiplier1 = 3250, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Walking"
    }, 
    ["Ninja Tri-Demon"] = {
        Image = "rbxassetid://127069975673790", 
        Multiplier1 = 3900, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    ["Sakura Queen"] = {
        Image = "rbxassetid://98080780978746", 
        Multiplier1 = 8000, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Flying"
    }, 
    ["Sakura Dominator"] = {
        Image = "rbxassetid://95682303474561", 
        Multiplier1 = 25000, 
        Multiplier2 = 1.5, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        InfoText = "1 in 333,333", 
        BigFrame = true
    }, 
    ["Fire Ninja"] = {
        Image = "rbxassetid://107939016426872", 
        Multiplier1 = 5000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Sensei Panda"] = {
        Image = "rbxassetid://94077142996547", 
        Multiplier1 = 5300, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    ["Monkey Warrior"] = {
        Image = "rbxassetid://73192404694353", 
        Multiplier1 = 5900, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    ["Bear Bender"] = {
        Image = "rbxassetid://105004500063366", 
        Multiplier1 = 6500, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Silent Assassin"] = {
        Image = "rbxassetid://74440453673469", 
        Multiplier1 = 6900, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Walking"
    }, 
    ["Water Beast"] = {
        Image = "rbxassetid://109013319315406", 
        Multiplier1 = 7500, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Walking"
    }, 
    Samureye = {
        Image = "rbxassetid://100325357446601", 
        Multiplier1 = 13000, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Flying"
    }, 
    ["Divine Dragon"] = {
        Image = "rbxassetid://100128323334713", 
        Multiplier1 = 26000, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        InfoText = "1 in 500,000", 
        BigFrame = true
    }, 
    ["Raging Claw"] = {
        Image = "rbxassetid://128714100076093", 
        Multiplier1 = 40000, 
        Multiplier2 = 1.5, 
        Rarity = "Secret II", 
        Movement = "Flying", 
        InfoText = "1 in 1,000,000", 
        BigFrame = true
    }, 
    ["Ash Dog"] = {
        Image = "rbxassetid://73842808662965", 
        Multiplier1 = 10000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Bone Bull"] = {
        Image = "rbxassetid://102629198736649", 
        Multiplier1 = 11700, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    ["Ember Inkling"] = {
        Image = "rbxassetid://70992349348376", 
        Multiplier1 = 12100, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Magmawrath = {
        Image = "rbxassetid://70570216541234", 
        Multiplier1 = 14000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Bone Cat"] = {
        Image = "rbxassetid://100352616448665", 
        Multiplier1 = 16000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Walking"
    }, 
    ["Magma Empyreus"] = {
        Image = "rbxassetid://94577333942712", 
        Multiplier1 = 21500, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Walking"
    }, 
    ["Hydra Magma Empyreus"] = {
        Image = "rbxassetid://96368966639063", 
        Multiplier1 = 26000, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    ["King Emblazed"] = {
        Image = "rbxassetid://106283368180305", 
        Multiplier1 = 35000, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Flying"
    }, 
    Magmasaur = {
        Image = "rbxassetid://135210155758717", 
        Multiplier1 = 80000, 
        Multiplier2 = 1.5, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        UseViewport = true, 
        InfoText = "1 in 500,000", 
        BigFrame = true
    }, 
    ["Caramel Bunny"] = {
        Image = "rbxassetid://121822804837788", 
        Multiplier1 = 30000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Vanilla Pluff"] = {
        Image = "rbxassetid://111107924739864", 
        Multiplier1 = 33000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Cotton Candy Pop"] = {
        Image = "rbxassetid://108922057342039", 
        Multiplier1 = 37000, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    ["Blueberry Taffy"] = {
        Image = "rbxassetid://70701637321934", 
        Multiplier1 = 45000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Waffle Knight"] = {
        Image = "rbxassetid://95351149337812", 
        Multiplier1 = 50000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Molten Coffee Dragon"] = {
        Image = "rbxassetid://103364208918704", 
        Multiplier1 = 60000, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    ["Bubblegum Chaos"] = {
        Image = "rbxassetid://82629576679209", 
        Multiplier1 = 88000, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Flying"
    }, 
    ["Candy God"] = {
        Image = "rbxassetid://108532164936872", 
        Multiplier1 = 150000, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        InfoText = "1 in 250,000", 
        BigFrame = true
    }, 
    ["Chocolate Marauder"] = {
        Image = "rbxassetid://90028563937149", 
        Multiplier1 = 200000, 
        Multiplier2 = 1.5, 
        Rarity = "Secret II", 
        Movement = "Flying", 
        InfoText = "1 in 1,000,000", 
        BigFrame = true
    }, 
    Nemo = {
        Image = "rbxassetid://134013504474048", 
        Multiplier1 = 50000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Walrus = {
        Image = "rbxassetid://139713360755298", 
        Multiplier1 = 56000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Dolphin = {
        Image = "rbxassetid://105612178602507", 
        Multiplier1 = 70000, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    Starfish = {
        Image = "rbxassetid://85843115496121", 
        Multiplier1 = 100000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["King Crab"] = {
        Image = "rbxassetid://82360114241566", 
        Multiplier1 = 110000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Royal Jelly"] = {
        Image = "rbxassetid://122536971317543", 
        Multiplier1 = 125000, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    Sharkie = {
        Image = "rbxassetid://83936953523322", 
        Multiplier1 = 250000, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Flying"
    }, 
    ["Orca Dominator"] = {
        Image = "rbxassetid://101041557064127", 
        Multiplier1 = 625000, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        InfoText = "1 in 250,000", 
        BigFrame = true
    }, 
    ["King Kraken"] = {
        Image = "rbxassetid://88516855132675", 
        Multiplier1 = 2000000, 
        Multiplier2 = 1.5, 
        Rarity = "Secret II", 
        Movement = "Flying", 
        InfoText = "1 in 1,000,000", 
        BigFrame = true
    }, 
    ["Astronaut Dog"] = {
        Image = "rbxassetid://138073480588651", 
        Multiplier1 = 90000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Rocket Scientist"] = {
        Image = "rbxassetid://139176270312434", 
        Multiplier1 = 100000, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    Alien = {
        Image = "rbxassetid://107892208591967", 
        Multiplier1 = 140000, 
        Multiplier2 = 0, 
        Rarity = "Rare", 
        Movement = "Walking"
    }, 
    ["Tri-Eyed Alien"] = {
        Image = "rbxassetid://90739322821667", 
        Multiplier1 = 180000, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    ["Stellar Eye"] = {
        Image = "rbxassetid://117733983430755", 
        Multiplier1 = 220000, 
        Multiplier2 = 0, 
        Rarity = "Legendary", 
        Movement = "Flying"
    }, 
    ["UFO Alien"] = {
        Image = "rbxassetid://73597434614505", 
        Multiplier1 = 400000, 
        Multiplier2 = 0, 
        Rarity = "Mythical", 
        Movement = "Flying"
    }, 
    ["Luminary Star"] = {
        Image = "rbxassetid://75019913521776", 
        Multiplier1 = 1500000, 
        Multiplier2 = 1.2, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        InfoText = "1 in 250,000", 
        BigFrame = true
    }, 
    ["Cosmic Chaos"] = {
        Image = "rbxassetid://138920951828244", 
        Multiplier1 = 4444444, 
        Multiplier2 = 1.7, 
        Rarity = "Secret II", 
        Movement = "Flying", 
        InfoText = "1 in 1,000,000", 
        BigFrame = true
    }, 
    Penguin = {
        Image = "rbxassetid://13363634493", 
        Image_Golden = "rbxassetid://13363645431", 
        Multiplier1 = 7.4, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Polar Bear"] = {
        Image = "rbxassetid://12951986528", 
        Image_Golden = "rbxassetid://13363646326", 
        Multiplier1 = 7.5, 
        Multiplier2 = 0, 
        Rarity = "Common", 
        Movement = "Walking"
    }, 
    ["Frost Angel"] = {
        Image = "rbxassetid://12956829349", 
        Image_Golden = "", 
        Multiplier1 = 7.7, 
        Multiplier2 = 0, 
        Rarity = "Epic", 
        Movement = "Flying"
    }, 
    Serenity = {
        Image = "rbxassetid://90762813745343|[256, 512]", 
        Multiplier1 = 16.7, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        Huge = true
    }, 
    ["Lion God"] = {
        Image = "rbxassetid://12956831159", 
        Multiplier1 = 16.2, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        Huge = true
    }, 
    ["Forest Wyvern"] = {
        Image = "rbxassetid://12956830602", 
        Multiplier1 = 16.3, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        Huge = true
    }, 
    ["Frost Archangel"] = {
        Image = "rbxassetid://12956830893", 
        Multiplier1 = 16.4, 
        Multiplier2 = 0, 
        Rarity = "Secret I", 
        Movement = "Flying", 
        Huge = true
    }
};