return {
    Forest = {
        Price = 1000000, 
        Multi = 1.1, 
        Image = "rbxassetid://85954600584914", 
        Color = Color3.fromRGB(47, 255, 0)
    }, 
    Winter = {
        Price = 50000000, 
        Multi = 1.25, 
        Image = "rbxassetid://98813284837223", 
        Color = Color3.fromRGB(20, 200, 255)
    }, 
    Desert = {
        Price = 1000000000, 
        Multi = 1.5, 
        Image = "rbxassetid://75245231535722", 
        Color = Color3.fromRGB(255, 170, 0)
    }, 
    Jungle = {
        Price = 50000000000, 
        Multi = 1.75, 
        Image = "rbxassetid://100708393747094", 
        Color = Color3.fromRGB(0, 255, 85)
    }, 
    Heaven = {
        Price = 2500000000000, 
        Multi = 2, 
        Image = "rbxassetid://113514390946918", 
        Color = Color3.fromRGB(255, 255, 255)
    }, 
    Dojo = {
        Price = 75500000000000, 
        Multi = 2.5, 
        Image = "rbxassetid://104469676449048", 
        Color = Color3.fromRGB(255, 62, 245)
    }, 
    Volcano = {
        Price = 2.5E15, 
        Multi = 2.75, 
        Image = "rbxassetid://131481650603761", 
        Color = Color3.fromRGB(255, 115, 0)
    }, 
    Candy = {
        Price = 1.0E17, 
        Multi = 3, 
        Image = "rbxassetid://81440962341505", 
        Color = Color3.fromRGB(255, 0, 242)
    }, 
    Atlantis = {
        Price = 3.5E18, 
        Multi = 3.25, 
        Image = "rbxassetid://116784190019375", 
        Color = Color3.fromRGB(0, 166, 255)
    }, 
    Space = {
        Price = 1.25E20, 
        Multi = 4, 
        Image = "rbxassetid://100642842384876", 
        Color = Color3.fromRGB(106, 0, 255)
    }
};