return {
    Basic = {
        Color3.fromRGB(0, 195, 255), 
        20, 
        50
    }, 
    Common = {
        Color3.fromRGB(0, 195, 255), 
        20, 
        50
    }, 
    Rare = {
        Color3.fromRGB(0, 255, 13), 
        20, 
        50
    }, 
    Epic = {
        Color3.fromRGB(183, 0, 255), 
        25, 
        50
    }, 
    Legendary = {
        Color3.fromRGB(255, 162, 0), 
        25, 
        75
    }, 
    Mythical = {
        Color3.fromRGB(225, 0, 255), 
        33, 
        75
    }, 
    Godly = {
        Color3.fromRGB(255, 222, 35), 
        33, 
        100
    }, 
    Leaderboard = {
        Color3.fromRGB(255, 236, 89), 
        34, 
        100
    }, 
    Exclusive = {
        Color3.fromRGB(200, 0, 255), 
        33, 
        150
    }, 
    ["Secret I"] = {
        Color3.fromRGB(0, 0, 0), 
        35, 
        150
    }, 
    ["Secret II"] = {
        Color3.fromRGB(0, 0, 0), 
        35, 
        150
    }, 
    ["Secret III"] = {
        Color3.fromRGB(255, 28, 28), 
        40, 
        200
    }
};