return {
    Clicks = {
        Name = "Clicks", 
        Description = "Used to buy stuff", 
        Image = "rbxassetid://118072224565757", 
        Rarity = "Common"
    }, 
    Gems = {
        Name = "Gems", 
        Description = "Used to buy stuff", 
        Image = "rbxassetid://113484836329837", 
        Rarity = "Rare"
    }, 
    Rebirths = {
        Name = "Rebirths", 
        Description = "Multiplies against your pets increasing your click yield!", 
        Rarity = "Rare", 
        Image = "rbxassetid://108301846890116"
    }, 
    Tokens = {
        Name = "Tokens", 
        Description = "Premium Currency can be used to purchase gamepasses in future!", 
        Image = "rbxassetid://86758327309470", 
        Rarity = "Legendary"
    }, 
    PaidTokens = {
        Name = "Paid Tokens", 
        Description = "Premium Currency purchased with Robux! Can be combined with regular Tokens for purchases.", 
        Image = "rbxassetid://123442386698522", 
        Rarity = "Legendary"
    }
};