return {
    MythicEvent = {
        Duration = 60, 
        Name = "Mythic Event", 
        Type = "MythicEvent", 
        Image = "rbxassetid://84608180504095", 
        Description = "5x chance for Mythical pets!", 
        Color = Color3.fromRGB(255, 0, 0)
    }, 
    LuckEvent = {
        Duration = 60, 
        Name = "Luck Event", 
        Type = "LuckEvent", 
        Image = "rbxassetid://76904441212368", 
        Description = "3x Luck on all eggs!", 
        Color = Color3.fromRGB(0, 255, 0)
    }, 
    ClicksEvent = {
        Duration = 60, 
        Name = "Clicks Event", 
        Type = "ClicksEvent", 
        Image = "rbxassetid://91579894049688", 
        Description = "10x Clicks on all taps!", 
        Color = Color3.fromRGB(0, 150, 255)
    }, 
    TacoEvent = {
        Duration = 60, 
        Name = "Taco Tuesday", 
        Type = "TacoEvent", 
        Image = "rbxassetid://114219785745391", 
        Description = "2x Luck, 2x Mythics and 2x Clicks!", 
        Color = Color3.fromRGB(255, 200, 0)
    }
};