return {
    AnchorTimestamp = 1703462400, 
    ResetIntervalSec = 604800, 
    WindowSize = 9, 
    RewardPool = {
        {
            weight = 50, 
            Type = "Currency", 
            Name = "Tokens", 
            Amount = 500
        }, 
        {
            weight = 30, 
            Type = "Currency", 
            Name = "Tokens", 
            Amount = 2000
        }, 
        {
            weight = 10, 
            Type = "Item", 
            Name = "SuperLuck", 
            Amount = 1
        }, 
        {
            weight = 8, 
            Type = "Boost", 
            Name = "2xClicks10m", 
            Amount = 1
        }, 
        {
            weight = 2, 
            Type = "Pet", 
            PetId = "SecretCoin", 
            Amount = 1, 
            Tier = "Golden"
        }
    }
};