return {
    RegularTreat = {
        Name = "Treat", 
        Rarity = 1, 
        XP = 150, 
        Description = "Gives +15 XP to your pet!", 
        Image = "rbxassetid://133201045273760", 
        Difficulty = 1, 
        Lives = 4
    }, 
    BagOfTreats = {
        Name = "Treat Bag", 
        Rarity = 10, 
        XP = 550, 
        Description = "Gives +75 XP to your pet!", 
        Image = "rbxassetid://102137666348749", 
        Difficulty = 1, 
        Lives = 6
    }, 
    ExoticShard = {
        Name = "Exotic", 
        Rarity = 10000, 
        XP = 1000, 
        Description = "Gives +1000 XP to your pet!", 
        Image = "rbxassetid://87609389569610", 
        Gradient = "Lgbtq", 
        Difficulty = 2, 
        Lives = 8
    }, 
    ChristmasSpins = {
        Name = "Christmas Spins", 
        Rarity = "Mythical", 
        Description = "Used for spinning the Christmas Wheel!", 
        Image = "rbxassetid://130480064308196", 
        Gradient = "Lgbtq", 
        Difficulty = 2, 
        Lives = 8
    }, 
    EnchantCrystal = {
        Name = "Enchant Crystal", 
        Rarity = "Mythical", 
        Description = "Used for spinning Enchants (Atlantis)!", 
        Image = "rbxassetid://130087145769303"
    }, 
    ["New Years Gift"] = {
        Name = "New Years Gift", 
        Rarity = "Mythical", 
        Description = "This will open on New Years Eve! Recieved during Admin Abuse!", 
        Image = "rbxassetid://107307098169609"
    }
};