return {
    DigGame = {
        Items = {
            RegularTreat = {
                "Item", 
                50
            }, 
            BagOfTreats = {
                "Item", 
                50
            }
        }
    }, 
    MemoryMatch = {
        Items = {
            RegularTreat = {
                "Item", 
                50
            }, 
            BagOfTreats = {
                "Item", 
                50
            }
        }
    }
};