return {
    ChristmasDayBundle = {
        PackId = "ChristmasDayBundle", 
        ProductId = 3501785767, 
        Price = 99, 
        StartTime = 1767537551, 
        Duration = 537649, 
        MaxPurchases = 2, 
        SecretRewardPurchaseAmount = 2, 
        Rewards = {
            {
                Type = "Pet", 
                Name = "Starshine Warrior", 
                Amount = 1, 
                Tier = "Rainbow"
            }, 
            {
                Type = "Boost", 
                Name = "TacoPotion", 
                Amount = 5
            }, 
            {
                Type = "Boost", 
                Name = "Festive Luck II", 
                Amount = 5
            }, 
            {
                Type = "Boost", 
                Name = "Festive Tap I", 
                Amount = 15
            }, 
            {
                Type = "Boost", 
                Name = "Festive Rebirths I", 
                Amount = 10
            }
        }, 
        SecretReward = {
            Type = "Pet", 
            PetId = "2026 Star", 
            Name = "2026 Star", 
            Amount = 1, 
            Tier = "Normal"
        }
    }
};