return {
    Rewards = {
        Basic = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 2500
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 5000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck20", 
                    Amount = 1
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 12500
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion II", 
                    Amount = 1
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion", 
                    Amount = 1
                }
            }
        }, 
        Acorn = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 7500
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 15000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck20", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Gem Potion I", 
                    Amount = 1
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 37500
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion II", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion II", 
                    Amount = 1
                }, 
                {
                    Type = "Boost", 
                    Name = "Gem Potion I", 
                    Amount = 1
                }
            }
        }, 
        Safari = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 12500
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 25000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion II", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion", 
                    Amount = 2
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 62500
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 1
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion II", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Gem Potion II", 
                    Amount = 1
                }
            }
        }, 
        Forest = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 18000
                }, 
                {
                    Type = "Boost", 
                    Name = "Gem Potion I", 
                    Amount = 1
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion II", 
                    Amount = 2
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 36000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion II", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Gem Potion I", 
                    Amount = 2
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 90000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion II", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Gem Potion II", 
                    Amount = 3
                }
            }
        }, 
        Snowman = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 85600
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 171200
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 1
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion II", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Rebirth Potion I", 
                    Amount = 1
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 428000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 3
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion III", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Gem Potion II", 
                    Amount = 2
                }
            }
        }, 
        Cactus = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 1000000
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 2000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 3
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion III", 
                    Amount = 1
                }, 
                {
                    Type = "Boost", 
                    Name = "Gem Potion II", 
                    Amount = 1
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 5000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 5
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion III", 
                    Amount = 3
                }, 
                {
                    Type = "Boost", 
                    Name = "Gem Potion III", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Egg Incubator", 
                    Amount = 1
                }
            }
        }, 
        Poison = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 3500000
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 7000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 5
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion III", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Rebirth Potion II", 
                    Amount = 1
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 17500000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck20", 
                    Amount = 10
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion", 
                    Amount = 5
                }, 
                {
                    Type = "Boost", 
                    Name = "Gem Potion I", 
                    Amount = 3
                }
            }
        }, 
        Holy = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 15000000
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 30000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Rebirth Potion II", 
                    Amount = 1
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 750000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck20", 
                    Amount = 10
                }, 
                {
                    Type = "Boost", 
                    Name = "Octo Incubator", 
                    Amount = 1
                }
            }
        }, 
        Sakura = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 55000000
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 110000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck20", 
                    Amount = 15
                }, 
                {
                    Type = "Boost", 
                    Name = "Rebirth Potion I", 
                    Amount = 2
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 275000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 3
                }
            }
        }, 
        Elemental = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 150000000
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 300000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck20", 
                    Amount = 3
                }, 
                {
                    Type = "Boost", 
                    Name = "Rebirth Potion II", 
                    Amount = 3
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 750000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 5
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion III", 
                    Amount = 2
                }
            }
        }, 
        Magma = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 440000000
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 880000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion II", 
                    Amount = 3
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 5200000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 5
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion III", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Octo Incubator", 
                    Amount = 1
                }
            }
        }, 
        Candy = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 740000000
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 1440000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 3
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion III", 
                    Amount = 4
                }, 
                {
                    Type = "Boost", 
                    Name = "Octo Incubator", 
                    Amount = 5
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 2500000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion III", 
                    Amount = 5
                }, 
                {
                    Type = "Boost", 
                    Name = "Rebirth Potion III", 
                    Amount = 2
                }
            }
        }, 
        Atlantis = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 1440000000
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 2500000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 3
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion III", 
                    Amount = 4
                }, 
                {
                    Type = "Boost", 
                    Name = "Octo Incubator", 
                    Amount = 5
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 18500000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Rebirth Potion III", 
                    Amount = 5
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 2
                }, 
                {
                    Type = "Boost", 
                    Name = "Octo Incubator", 
                    Amount = 1
                }
            }
        }, 
        Space = {
            Normal = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 32000000000
                }
            }, 
            Golden = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 64000000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 6
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion III", 
                    Amount = 5
                }, 
                {
                    Type = "Boost", 
                    Name = "Octo Incubator", 
                    Amount = 2
                }
            }, 
            Rainbow = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 160000000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Rebirth Potion III", 
                    Amount = 5
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion III", 
                    Amount = 3
                }, 
                {
                    Type = "Boost", 
                    Name = "Octo Incubator", 
                    Amount = 1
                }
            }
        }, 
        Secrets = {
            Complete = {
                {
                    Type = "Currency", 
                    Name = "Gems", 
                    Amount = 10500000000000
                }, 
                {
                    Type = "Boost", 
                    Name = "Luck Potion II", 
                    Amount = 5
                }, 
                {
                    Type = "Boost", 
                    Name = "Tap Potion II", 
                    Amount = 5
                }, 
                {
                    Type = "Boost", 
                    Name = "Octo Incubator", 
                    Amount = 5
                }
            }
        }
    }, 
    GetRewards = function(v0, v1, v2) --[[ Line: 277 ]] --[[ Name: GetRewards ]]
        if not v0.Rewards[v1] then
            return nil;
        else
            return v0.Rewards[v1][v2];
        end;
    end, 
    GetEggRewards = function(v3, v4) --[[ Line: 286 ]] --[[ Name: GetEggRewards ]]
        return v3.Rewards[v4];
    end, 
    HasClaimed = function(_, v6, v7, v8) --[[ Line: 291 ]] --[[ Name: HasClaimed ]]
        if not v6.PetIndexRewards then
            return false;
        elseif not v6.PetIndexRewards[v7] then
            return false;
        else
            return v6.PetIndexRewards[v7][v8] == true;
        end;
    end
};