return {
    [1] = {
        Title = "Starter", 
        Icon = "110235271674289", 
        Multiplier = 1
    }, 
    [2] = {
        Title = "Wooden", 
        Icon = "78262050700575", 
        Multiplier = 1
    }, 
    [3] = {
        Title = "Silver", 
        Icon = "104288518457136", 
        Multiplier = 1
    }, 
    [4] = {
        Title = "Gold", 
        Icon = "70930102867935", 
        Multiplier = 1
    }, 
    [5] = {
        Title = "Diamond", 
        Icon = "91579894049688", 
        Multiplier = 1
    }, 
    [6] = {
        Title = "Heavenly", 
        Icon = "105999739686456", 
        Multiplier = 1
    }, 
    [7] = {
        Title = "Galactic", 
        Icon = "108061416237636", 
        Multiplier = 1
    }, 
    [8] = {
        Title = "Magma", 
        Icon = "133010620354245", 
        Multiplier = 1
    }, 
    [9] = {
        Title = "Dark-Matter", 
        Icon = "74819470284279", 
        Multiplier = 1
    }, 
    [10] = {
        Title = "Prismatic", 
        Icon = "91671492635289", 
        Multiplier = 1
    }
};