return {
    Main = {
        Rewards = {
            [1] = {
                Price = 100, 
                Reward = {
                    "Pet", 
                    "Dog"
                }
            }, 
            [2] = {
                Price = 100
            }, 
            [3] = {
                Price = 100, 
                Reward = {
                    "Pet", 
                    "Anglerfish"
                }
            }, 
            [4] = {
                Price = 100, 
                Reward = {
                    "Pet", 
                    "Lion"
                }
            }, 
            [5] = {
                Price = 100, 
                Reward = {
                    "Pet", 
                    "Fox"
                }
            }, 
            [6] = {
                Price = 100
            }, 
            [7] = {
                Price = 100, 
                Reward = {
                    "Pet", 
                    "Octopus"
                }
            }, 
            [8] = {
                Price = 100, 
                Reward = {
                    "Pet", 
                    "Flaming Demon"
                }
            }, 
            [9] = {
                Price = 100, 
                Reward = {
                    "Pet", 
                    "Serenity"
                }
            }, 
            [10] = {
                Price = 100, 
                Reward = {
                    "Pet", 
                    "Seaweed Monster"
                }
            }
        }
    }
};