return {
    Santas2025Gift = {
        PackId = "Santas2025Gift", 
        DeveloperProducts = {
            [1] = 3489427094, 
            [2] = 3489427395, 
            [3] = 3489427570
        }, 
        Rewards = {
            [1] = {
                Type = "Boost", 
                Name = "Festive Luck I", 
                Amount = 1, 
                DeveloperProduct = 0
            }, 
            [2] = {
                Type = "Currency", 
                Name = "Gems", 
                Amount = 10000000000, 
                DeveloperProduct = 1
            }, 
            [3] = {
                Type = "Boost", 
                Name = "Festive Tap I", 
                Amount = 2, 
                DeveloperProduct = 1
            }, 
            [4] = {
                Type = "Boost", 
                Name = "Luck Potion III", 
                Amount = 3, 
                DeveloperProduct = 2
            }, 
            [5] = {
                Type = "Boost", 
                Name = "Festive Tap I", 
                Amount = 3, 
                DeveloperProduct = 2
            }, 
            [6] = {
                Type = "Boost", 
                Name = "Festive Rebirths I", 
                Amount = 2, 
                DeveloperProduct = 2
            }, 
            [7] = {
                Type = "Boost", 
                Name = "Festive Luck II", 
                Amount = 5, 
                DeveloperProduct = 2
            }, 
            [8] = {
                Type = "Pet", 
                Name = "Nutcracker", 
                Tier = "Golden", 
                Amount = 1, 
                DeveloperProduct = 3
            }, 
            [9] = {
                Type = "Pet", 
                Name = "Celestial Candycane", 
                Amount = 1, 
                DeveloperProduct = 3
            }
        }
    }
};