return {
    [1] = {
        Name = "Spawn", 
        RequiredQuests = {
            "SpawnQuest1", 
            "SpawnQuest2"
        }, 
        ShowQuests = true, 
        Features = {
            "Upgrades", 
            "Index"
        }
    }, 
    [2] = {
        Name = "Forest", 
        RequiredQuests = {
            "SpawnQuest1", 
            "SpawnQuest2"
        }, 
        ShowQuests = true
    }
};